# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/sm8150-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter r5q beyond0qlte beyond1qlte beyond2qlte d1q d2q,$(TARGET_DEVICE)),)

endif
