# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/sm8150-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter r5q,$(TARGET_DEVICE)),)

endif
