# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/sm8250-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter c2q,$(TARGET_DEVICE)),)

endif
